apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-worker-01-local-pv-1
  labels:
    opster.io/opensearch-cluster: dev-os-cluster
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-worker-02-local-pv-2
  labels:
    opster.io/opensearch-cluster: dev-os-cluster
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker-02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-worker-03-local-pv-3
  labels:
    opster.io/opensearch-cluster: dev-os-cluster
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker-03
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: dev-os-cluster-bootstrap-data-pv
 labels:
   opster.io/opensearch-cluster: dev-os-cluster
spec:
 capacity:
   storage: 1Gi
 volumeMode: Filesystem
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 local:
   path: /var/data/bootstrap
 nodeAffinity:
   required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname
         operator: In
         values:
         - k8s-worker-01
